### ISSUE TITLE
echo pusher-js

### ISSUE THREAD

**Issue by IbtsamAli** [jaouadballat/chatapp#3]
i have an error in npm install --save laravel-echo pusher-js
![11](https://user-images.githubusercontent.com/24366848/36061198-caa2ffa4-0e78-11e8-9489-064621727af2.PNG)

**Comment by jaouadballat** [comment]
may be you need to install the latest node version

**Comment by IbtsamAli** [comment]
when i run php artisan serve it only shows laravel title and no chat is open

**Comment by jaouadballat** [comment]
plz check route file to figure out where you need to go 
the reason why it show laravel title cuz you need to go to '/messages' route

**Comment by IbtsamAli** [comment]
now its working but only show two brackets on page i run
localhost:8080/messages

**Comment by jaouadballat** [comment]
read this documentation https://codeburst.io/realtime-chat-app-with-laravel-5-4-and-vuejs-2-using-pusher-d53d7f3a8086

**Comment by IbtsamAli** [comment]
i apply all these steps properly

**Comment by IbtsamAli** [comment]
this is the output

**Comment by IbtsamAli** [comment]
i dont put code on server
